# Generated by Django 5.2.8 on 2025-12-11 12:10

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid_number', models.IntegerField(blank=True, help_text="UID de l'utilisateur dans LDAP", null=True, unique=True, verbose_name='UID number LDAP')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='UserName en LDAP')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name LDAP')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name LDAP')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name LDAP')),
                ('ldap_dn', models.CharField(blank=True, help_text="DN complet de l'utilisateur dans LDAP", max_length=255, null=True, verbose_name='Distinguished Name LDAP')),
                ('ldap_role', models.CharField(blank=True, help_text='Le role d un utilisateur dans ldap', max_length=255, null=True, verbose_name='Role LDAP')),
                ('ldap_cn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Distinguished Name LDAP')),
                ('last_ldap_sync', models.DateTimeField(auto_now=True, verbose_name='Dernière synchronisation LDAP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur LDAP',
                'verbose_name_plural': 'Utilisateurs LDAP',
                'db_table': 'auth_ldap_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
