# Generated by Django 5.0 on 2025-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuser',
            name='ldap_dn',
            field=models.CharField(blank=True, help_text="DN complet de l'utilisateur dans LDAP", max_length=255, null=True, unique=True, verbose_name='Distinguished Name LDAP'),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='ldap_roles',
            field=models.JSONField(blank=True, default=list, help_text='Liste des rôles récupérés depuis LDAP', verbose_name='Rôles LDAP'),
        ),
        migrations.AlterModelTable(
            name='ldapuser',
            table='auth_ldap_user',
        ),
    ]
