# Generated by Django 5.0 on 2025-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ldapuser_ldap_dn_alter_ldapuser_ldap_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuser',
            name='ldap_role',
            field=models.CharField(blank=True, help_text='Le role d un utilisateur dans ldap', max_length=255, null=True, unique=True, verbose_name='Role LDAP'),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='ldap_roles',
            field=models.JSONField(blank=True, default=list, help_text='role récupérés depuis LDAP', verbose_name='Rôles LDAP'),
        ),
    ]
