# Generated by Django 5.0 on 2025-11-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_ldapuser_ldap_role_alter_ldapuser_ldap_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapuser',
            name='ldap_roles',
        ),
    ]
