# Generated by Django 5.0 on 2025-11-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_ldapuser_ldap_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='ldap_role',
            field=models.CharField(blank=True, help_text='Le role d un utilisateur dans ldap', max_length=255, null=True, verbose_name='Role LDAP'),
        ),
    ]
