# Generated by Django 5.0 on 2025-11-26 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bot', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('etat', models.IntegerField()),
                ('descritpion', models.TextField()),
                ('assigned_user', models.CharField(max_length=255)),
            ],
        ),
    ]
