# Generated by Django 5.0 on 2025-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='id',
        ),
        migrations.AlterField(
            model_name='bots',
            name='id_bot',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
