# Generated by Django 5.0 on 2025-11-26 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_bots_id_alter_bots_id_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bots',
            name='killed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bots',
            name='etat',
            field=models.IntegerField(choices=[(0, 'Pause'), (1, 'Run'), (2, 'Killed')]),
        ),
    ]
