# Generated by Django 5.0 on 2025-11-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bots_created_at_bots_killed_at_alter_bots_etat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bots',
            old_name='etat',
            new_name='status',
        ),
    ]
