# Generated by Django 5.0 on 2025-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_rename_etat_bots_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='assigned_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
