# Generated by Django 5.0 on 2025-11-26 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BotFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bot_filter', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('required_all', models.BooleanField()),
                ('action', models.IntegerField(choices=[(0, 'Delete'), (1, 'Save')])),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='bots.bots')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operator', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='bot_filter.field')),
            ],
        ),
        migrations.CreateModel(
            name='BotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rule', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('value', models.TextField()),
                ('bot_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bot_filter.botfilter')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='bot_filter.field')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_rules', to='bot_filter.operator')),
            ],
        ),
    ]
