# Generated by Django 5.0 on 2025-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botfilter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='botrule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='id',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='id',
        ),
        migrations.AlterField(
            model_name='botfilter',
            name='id_bot_filter',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='botrule',
            name='id_rule',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='id_field',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id_operator',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
