# Generated by Django 5.0 on 2025-11-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_filter', '0002_remove_botfilter_id_remove_botrule_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botfilter',
            old_name='id_bot_filter',
            new_name='id_filter',
        ),
    ]
